ARG="${LOGNAME}"
"$ARG"
'"$ARG"'
      '$USER'   '   "$USER  " '    
      '$USER'   '   "$USER  " ''$USER'    
      '$USER'   '   "$USER  " ''$USER'"$USER"    
      '$USER'   '   "$USER  " ''$USER'"$USER"    
      '$USER'   '   "$USER  " ''$USER' "$USER"    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
     " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $USER "    
      '$USER'   '   "$USER  " ''$USER' " $LOGNAME"    
      '$USER'   '   "$USER  " ''$USER' " $USER"    
      '$USER'   '   "$USER  " ''$USER' " $HOME"    
      '$USER'   '"$USER  "'    '$USER'     "$HOME"    
      '$USER'   '"$USER  "'    '$USER'     "$HOME"    
      '$USER'   '"$USER  "'    '$USER'     "$HOME"    
      '$USER'   '"$USER  "'    '$USER'     "$HOME"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'       "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
"$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$USER"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'    '$USER'     "$ARG"    
      '$USER'   '"$USER  "'      "$ARG"    
      '$USER'   '"$USER  "'      "$ARG"    
